# Generated by Django 4.1.1 on 2022-09-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='state',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='seat',
            field=models.IntegerField(null=True),
        ),
    ]
